### ISSUE TITLE
Projet - Question 1

### ISSUE THREAD

**Issue by p9f** [hivert/CombiFIIL#2]
Bonjour, 

Pourriez vous s'il vous plait détailler la question 1 ? Je ne suis pas sur de saisir quel est le travail / résultat demandé.
De quel 8 non-terminaux s'agit-il ?

Merci d'avance,

**Comment by VivianePons** [comment]
Il y avait une petite erreur dans la question, je viens de corriger, on demande maintenant le résultat de count pour les 8 non terminaux des mots de Fibonnacci et pour les 3 non temrinaux de la grammaire des arbres binaires.
