### ISSUE TITLE
Project Q15 - do we need to implement ourself the caching ?

### ISSUE THREAD

**Issue by p9f** [hivert/CombiFIIL#3]
All is in the title.
As far as I understand, [functools](https://docs.python.org/3/library/functools.html) (present by default in python3.6) give us exactly what we need, with a one line decorator.
Can we use it, or do we need to re-implement ourself the same ? It sound like reinvent the wheel...
Thanks

**Comment by VivianePons** [comment]
You can use every tool or library you see fit. If you do use it, you should try to understand how it works, what it caches and when to see how efficient it is for your problem.

Of course, it is also possible to develop a handmade solution.

You can even do both and see which one is more efficient...
